NEO-51318: fix SimpleJson serialization issues
adobe/acc-js-sdk pull request #54
Opened 2022-11-19 09:21 UTC by mkiki

## Description

I discovered a few more issues in the XML to JSON serialization.
More documentation: https://opensource.adobe.com/acc-js-sdk/simpleJson.html
 

when XML element has both a text content and attributes or child elements
when root element has only text
when XML element has both an attribute and a child element with the same name
when array contains element which only have text
when XML is formatted (and therefore has insignificant whitespaces)
XML collections (i.e. when root node ends with “-collection”) would sometimes contain a JSON property “#text”
 

So far the SimpleJSon rules where:

 

XML Attributes are transformed to JSON properties without the “@” prefix. The rationale is that Campaign generally uses attributes, so we make the attribute syntax the most straightforward.
XML Elements are transformed to JSON objects or arrays if the element appears more than once
XML Elements containing only text are transformed to JSON properties with the “$” prefix. The rationale is that Campaign usually does not have XML elements containing both text and children elements and therefore the JSON syntax remains simple in the common case
 

I’m adding the following rules

 

When XML element has both a XML child element and an attribute with the same name, the attribute will have the “@” prefix. This assume that both attribute and element are actually present (possibly empty) in the XML
XML elements containing only text will continue to be transformed to JSON properties with the “$” prefix. Whitespaces in the text content are unchanged.
XML elements containing text and either attributes or children will be transformed to JSON objects having the “$” property which will contain the text. The whitespaces in the text will be removed
When XML element contain multiple XML text nodes, they will be concatenated and seen as one in JSON. This is not recursive. Each text node is considered independently regarding whitespaces
CDATA nodes will be considered as text nodes but for which whitespaces are never removed
Whitespace removal consist on removing the “ “, “\t”, “\n” and “\r” characters at the beginning or the end of the text
 

Here are a few examples of what's expected

 
```
expect(toJSON('<root>Hello</root>')).toEqual({ $: "Hello" });
expect(toJSON('<ctx><delivery>Hello</delivery></ctx>')).toEqual({ "$delivery": "Hello" });
expect(toJSON('<delivery transaction="0">0</delivery>')).toEqual({ "transaction": "0", "$": "0" });
expect(toJSON('<ctx><delivery transaction="0">0</delivery></ctx>')).toEqual({delivery: { "transaction":"0", "$": "0" }});
expect(toJSON('<ctx><delivery>Hello<child name="world"/></delivery></ctx>')).toEqual({delivery: { "$":"Hello", child:
{ name: "world" }
}});
expect(toJSON('<ctx><delivery><child name="world"/>Hello</delivery></ctx>')).toEqual({delivery: { "$":"Hello", child:
{ name: "world" }
}});
expect(toJSON('<root><delivery>Hello<child/>World</delivery></root>')).toEqual({ delivery: { $:"HelloWorld", child:{} } });
```

## Motivation and Context

* Processing report data (see https://github.com/adobe/acc-js-sdk/pull/50)
* The report data payload contain XML element which have both attributes and text content which was not supported before

## How Has This Been Tested?

* New unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

This change is actually a breaking change since it changes how JSON serialization works. However, it only changes for cases which were missing / buggy / not properly defined. So it should be backwards compatible. If not, the code that it breaks was probably not working / not safe anyways.

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-22 11:42 UTC, rahuljain936 commented on docs/simpleJson.html
> +<p>If an element contains another element and an attribute which have the same name, the attribute name is prefixed with the "@" character</p>
Can add a test case for this case as well.

2022-11-28 07:32 UTC, mukulgupta21 requested changes
Can we use [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim#return_value) instead of our own implementation.
Other than that, I have only some typos and cosmetic change suggestions.

2022-11-28 07:32 UTC, mukulgupta21 commented on src/util.js
> +  static removeXmlWhiteSpaces(text) {
Couldn't we have used `text.trim()` instead?
It handles both whitespace and line terminators.
[Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim#return_value)

2022-11-28 07:32 UTC, mukulgupta21 commented on src/util.js
> +    return text;
```suggestion
    if (!text) return text;
    var first = 0, last = text.length - 1;
    while (first <= last) {
      var c = text[first];
      if (c === ' ' || c === '\t' || c === '\n' || c === '\r') { first = first + 1; continue; }
      c = text[last];
      if (c === ' ' || c === '\t' || c === '\n' || c === '\r') { last = last - 1; continue; }
      break;
    }
    text = text.substring(first, last + 1);
    return text;
```

2022-11-28 07:32 UTC, mukulgupta21 commented on test/domUtil.test.js
> +            //expect(fromJSON({ "$delivery": "World", "delivery": { $: "Hello" } })).toBe("<root><delivery>Hello</delivery></root>");
Debug code? Perhaps, your intention is to fix this case in the future. We could leave it like that then.
The asserted behaviour seems correct to me.

2022-11-28 07:32 UTC, mukulgupta21 commented on src/domUtil.js
> +                    // Whitesapce trimming rule: alwasy trim for the root node, and trim for non-root nodes
```suggestion
                    // Whitespace trimming rule: always trim for the root node, and trim for non-root nodes
```

2022-11-28 08:59 UTC, merged