Neo 53889 adding abortable support
adobe/acc-js-sdk pull request #74
Opened 2023-02-02 06:27 UTC by infinity1013

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-02-03 04:51 UTC, gauravmakkar requested changes

2023-02-03 04:51 UTC, gauravmakkar commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
please remove this file. js sdk uses package-lock.json

2023-02-03 04:51 UTC, gauravmakkar commented on src/soap.js
>       */
jsdoc needs to be updated for signal

2023-02-03 04:51 UTC, gauravmakkar commented on src/client.js
>       */
jsdoc needs to be updated for signal

2023-02-03 13:47 UTC, gauravmakkar commented
@infinity1013 don't you think the docs should be updated for the usage of this feature? It should be added even in the best practises as well.

2023-02-17 11:12 UTC, mkiki requested changes

2023-02-17 11:12 UTC, mkiki commented on src/transport.js
> +        ...(options.signal && {signal : options.signal})
Why not write "signal: options.signal" ?
The SDK does not currently use any build tools, and hence trying to keep the syntax as simple as possible.

2023-02-17 11:12 UTC, mkiki commented on src/soap.js
> +            ...(this._pushDownOptions && {signal : this._pushDownOptions.signal})
I do not think this is necessary. The pushdown mechanism should pass the signal attirbute automatically down to the transport layer

2023-02-17 11:12 UTC, mkiki commented on src/transport.js
> +        ...(options.signal && {signal : options.signal})
Also, what about the axis transport layer? Both fetch and axis transport layers should be updated

2023-02-17 11:12 UTC, mkiki commented on docs/transport.html
> +<p>The second parameter is an set of additional parameters that have been pushed down to the transport layer (see the <b>Pushdown</b> paragraph for more details). In particular, the <b>timeout</b> an
Can you also document how to abort requests? Look at the timeout.html for an example.
Add a new "Aborting queries" menu in Advanced topics section, just like this is done for timeouts. Document how the mechansim works and give a few exampels.

2023-02-21 14:12 UTC, mkiki requested changes
Hi Aadarsh, there are a few details in the documentation, and then I think it's all good.

2023-02-21 14:12 UTC, mkiki commented on docs/abortRequest.html
> +---
You also need to update navigation.yml to make sure this new page appears in the doc menu. You can add an entry right after the timeouts.html entry

2023-02-21 14:12 UTC, mkiki commented on docs/abortRequest.html
> +<h3>Aborting API requests in fetch</h3>
You should start with &lt;h1> for top level titles, not &lt;h3>

2023-02-21 14:12 UTC, mkiki commented on docs/abortRequest.html
> +<h3>Aborting API requests in Axios</h3>
You should start with &lt;h1> for top level titles, not &lt;h3>

2023-02-21 14:12 UTC, mkiki commented on docs/abortRequest.html
> +<h2>Passing AbortSignal via PushDown Mechanism</h2>
You should start with &lt;h1> for top level titles, not &lt;h3>

2023-02-21 14:12 UTC, mkiki commented on docs/abortRequest.html
> +client.NLWS.pushDown({ signal: instance.current.signal }).xtkQueryDef.create(queryDef)
I think the example could show the creation of the signal object and how to actually abort the request

2023-02-28 17:51 UTC, merged